fastfony_identity:
    user:
        # Your custom User entity class extends Fastfony\IdentityBundle\Entity\Identity\User (optional)
        #class: 'App\Entity\User'

    role:
        # Your custom Role entity class extends Fastfony\IdentityBundle\Entity\Identity\Role (optional)
        #class: 'App\Entity\Role'
        # Default role assigned to new users (if you want to assign one different from ROLE_USER)
        #default_role: 'ROLE_ADMIN'

    group:
        # Your custom Group entity class extends Fastfony\IdentityBundle\Entity\Identity\Group (optional)
        #class: 'App\Entity\Group'
