# Example configuration for FastfonyIdentityBundle
# Add this to your config/packages/fastfony_identity.yaml

fastfony_identity:
    user:
        # Your custom User entity class
        class: 'App\Entity\User'

    role:
        # Your custom Role entity class
        class: 'App\Entity\Role'
        # Default role assigned to new users
        default_role: 'ROLE_USER'

    group:
        # Your custom Group entity class
        class: 'App\Entity\Group'
