services:
    _defaults:
        autowire: true
        autoconfigure: true

    Fastfony\IdentityBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/FastfonyIdentityBundle.php'
