services:
    _defaults:
        autowire: true
        autoconfigure: true

    Fastfony\IdentityBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/FastfonyIdentityBundle.php'

    # Services
    Fastfony\IdentityBundle\Service\UserManager:
        public: true
        arguments:
            $userClass: '%fastfony_identity.user.class%'

    Fastfony\IdentityBundle\Service\RoleManager:
        public: true
        arguments:
            $roleClass: '%fastfony_identity.role.class%'

    Fastfony\IdentityBundle\Service\GroupManager:
        public: true
        arguments:
            $groupClass: '%fastfony_identity.group.class%'

    # Event Listeners
    Fastfony\IdentityBundle\EventListener\LoginListener:
        tags:
            - { name: kernel.event_subscriber }
