services:
    _defaults:
        autowire: true
        autoconfigure: true

    Fastfony\IdentityBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/FastfonyIdentityBundle.php'

    # Manager services with injected entity class names
    Fastfony\IdentityBundle\Manager\UserManager:
        public: true
        arguments:
            $userClass: '%fastfony_identity.user.class%'

    Fastfony\IdentityBundle\Manager\RoleManager:
        public: true
        arguments:
            $roleClass: '%fastfony_identity.role.class%'

    Fastfony\IdentityBundle\Manager\GroupManager:
        public: true
        arguments:
            $groupClass: '%fastfony_identity.group.class%'
